name: Ping API Render

on:
  schedule:
    - cron: '*/5 * * * *'  # A cada 5 minutos (UTC)
  workflow_dispatch:        # Permite executar manualmente também

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Requisição para manter API ativa
        run: |
          curl -s https://lubribot.onrender.com/ping > /dev/null